---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: parasol-insurance
type: Opaque
stringData:
  my-secret-data: thisisasecretvalue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: parasol-insurance
data:
  my-configmap-data: thisisaconfigmapvalue
